

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress
      - cadvisor

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks:
      - inception_net
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    restart: always


  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    networks:
      - inception_net
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    env_file:
      - .env
    restart : always

# BONUS {

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/
    ports:
      - 21:21
      - 21100-21110:21100-21110
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    env_file:
      - .env
    restart : always
    depends_on:
      - wordpress

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
# }


volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME_PATH}/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME_PATH}/data/mariadb
      o: bind


networks:
  inception_net:
    driver: bridge


